export const defaultProps = {
  inputs: [
    {
      type: "multipleText",
      name: "name",
      label: "الإسم و اللقب",
      placeHolder: "placeHolder",
      required: true,
      defaultValue: "",
      readOnly: false,
      hidden: false,
      multiple: true,
    },
    {
      type: "phoneNumber",
      name: "phoneNumber",
      label: "Phone Number",
      required: true,
      defaultValue: "26675997",
    },
    {
      type: "cinNumber",
      name: "cinNumber",
      label: "CIN Number",
      required: true,
      defaultValue: "61876257",
    },
    {
      type: "address",
      name: "address",
      label: "Address",
      required: true,
      defaultValue: "سهلول سوسة",
    },
    {
      type: "birthDate",
      name: "birthDate",
      label: "Birth Date",
      readOnly: false,
      hidden: false,
      required: true,
      defaultValue: new Date().toISOString().substr(0, 10),
    },
    {
      type: "select",
      name: "select",
      label: "Select",
      required: true,
      options: [
        { value: "option1", label: "option1" },
        { value: "option2", label: "option2" },
        { value: "option3", label: "option3" },
      ],
    },
    {
      type: "checkboxGroup",
      name: "checkboxGroup",
      label: "Checkbox Group",
      required: true,
      options: [
        { value: "option1", label: "option1" },
        { value: "option2", label: "option2" },
        { value: "option3", label: "option3" },
      ],
    },
    {
      type: "radioGroup",
      name: "radioGroup",
      label: "Radio Group",
      required: true,
      options: [
        { value: "option1", label: "option1" },
        { value: "option2", label: "option2" },
        { value: "option3", label: "option3" },
      ],
    },
    {
      type: "textArea",
      name: "textArea",
      label: "Text Area",
      required: true,
    },
    {
      type: "location",
      name: "location",
      label: "Location",
      required: true,
    },
    {
      type: "file",
      name: "file",
      label: "File",
      required: true,
      multiple: false,
    },
    {
      type: "file",
      name: "multipleFiles",
      label: "Multiple File",
      required: true,
      multiple: true,
      defaultValue: [""],
    },
  ],
  onSubmit: (values) => {

  },
  submitButtonLabel: "Submit",
};
